# Generated by Django 3.2.4 on 2021-06-15 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('bio', models.TextField(blank=True)),
                ('image_cover', models.ImageField(blank=True, upload_to='profile/cover/%Y/%m/%d/')),
                ('image_profile', models.ImageField(blank=True, upload_to='profile/profile/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
